export const products = [
  // 📱 Mobile (4)
  {
    id: 1,
    name: "iPhone 15 Pro",
    description: "Apple A17 Pro chip smartphone",
    category: "mobile",
    price: 3200,
    image: "https://picsum.photos/seed/iphone15/400/400",
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    description: "Flagship Android smartphone",
    category: "mobile",
    price: 3000,
    image: "https://picsum.photos/seed/s24ultra/400/400",
  },
  {
    id: 3,
    name: "Google Pixel 8 Pro",
    description: "AI-powered Google smartphone",
    category: "mobile",
    price: 2700,
    image: "https://picsum.photos/seed/pixel8/400/400",
  },
  {
    id: 4,
    name: "OnePlus 12",
    description: "High-performance flagship phone",
    category: "mobile",
    price: 2500,
    image: "https://picsum.photos/seed/oneplus12/400/400",
  },

  // 💻 Laptop (4)
  {
    id: 5,
    name: "MacBook Pro M3",
    description: "Powerful Apple silicon laptop",
    category: "laptop",
    price: 6000,
    image: "https://picsum.photos/seed/macbookm3/400/400",
  },
  {
    id: 6,
    name: "Dell XPS 15",
    description: "Premium Windows ultrabook",
    category: "laptop",
    price: 4500,
    image: "https://picsum.photos/seed/dellxps/400/400",
  },
  {
    id: 7,
    name: "HP Spectre x360",
    description: "Convertible touchscreen laptop",
    category: "laptop",
    price: 4000,
    image: "https://picsum.photos/seed/hpspectre/400/400",
  },
  {
    id: 8,
    name: "Lenovo ThinkPad X1 Carbon",
    description: "Business class ultralight laptop",
    category: "laptop",
    price: 4200,
    image: "https://picsum.photos/seed/thinkpadx1/400/400",
  },

  // 🎧 Accessories (4)
  {
    id: 9,
    name: "AirPods Pro (2nd Gen)",
    description: "Noise cancelling earbuds",
    category: "accessories",
    price: 900,
    image: "https://picsum.photos/seed/airpods/400/400",
  },
  {
    id: 10,
    name: "Sony WH-1000XM5",
    description: "Premium noise cancelling headphones",
    category: "accessories",
    price: 1200,
    image: "https://picsum.photos/seed/sonyheadphones/400/400",
  },
  {
    id: 11,
    name: "Logitech MX Master 3S",
    description: "Advanced wireless mouse",
    category: "accessories",
    price: 450,
    image: "https://picsum.photos/seed/logitechmouse/400/400",
  },
  {
    id: 12,
    name: "Apple Magic Keyboard",
    description: "Wireless keyboard for Mac",
    category: "accessories",
    price: 600,
    image: "https://picsum.photos/seed/magickeyboard/400/400",
  },

  // 📺 Electronics (4)
  {
    id: 13,
    name: "Sony Bravia 65” 4K TV",
    description: "Ultra HD Smart LED TV",
    category: "electronics",
    price: 6500,
    image: "https://picsum.photos/seed/sonybravia/400/400",
  },
  {
    id: 14,
    name: "PlayStation 5",
    description: "Next-gen gaming console",
    category: "electronics",
    price: 3500,
    image: "https://picsum.photos/seed/ps5/400/400",
  },
  {
    id: 15,
    name: "Xbox Series X",
    description: "Microsoft gaming console",
    category: "electronics",
    price: 3400,
    image: "https://picsum.photos/seed/xboxseriesx/400/400",
  },
  {
    id: 16,
    name: "Samsung 55” QLED TV",
    description: "Smart QLED television",
    category: "electronics",
    price: 5000,
    image: "https://picsum.photos/seed/qledtv/400/400",
  },

  // ⌚ Wearables (4)
  {
    id: 17,
    name: "Apple Watch Series 9",
    description: "Advanced health smartwatch",
    category: "wearables",
    price: 1200,
    image: "https://picsum.photos/seed/applewatch9/400/400",
  },
  {
    id: 18,
    name: "Samsung Galaxy Watch 6",
    description: "Smart fitness wearable",
    category: "wearables",
    price: 1000,
    image: "https://picsum.photos/seed/galaxywatch6/400/400",
  },
  {
    id: 19,
    name: "Fitbit Charge 6",
    description: "Fitness and activity tracker",
    category: "wearables",
    price: 700,
    image: "https://picsum.photos/seed/fitbit6/400/400",
  },
  {
    id: 20,
    name: "Garmin Forerunner 965",
    description: "Advanced GPS sports watch",
    category: "wearables",
    price: 1500,
    image: "https://picsum.photos/seed/garmin965/400/400",
  },
];
